# Site settings
# These are used to personalize your new site.
title: Bryce Furrow # your name here
logo: "/images/ProfessionalPic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2024)
  <br /><br />
  <a href="https://example.com/resume">View My Resume</a>
repository: "BFurrow-Collab/BFurrow-Collab.github.io"
github_username:  BFurrow-Collab # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
# <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
# Build setting
theme: jekyll-theme-minimal

